"""Graph Risk Engine.

Builds a startup-counterparty network with networkx, derives
PageRank / degree-centrality / clustering-coefficient features, combines
them with relationship features per the spec 3-1 Network Credit Score
formula, and trains scikit-learn models to predict:
  - counterparty_risk: low / medium / high  (GradientBoostingClassifier)
  - network_credit_score: 0-100             (GradientBoostingRegressor)

NOTE (future extension point): a GNN (e.g. GraphSAGE / GAT over the
startup-counterparty-investor graph) could replace the hand-engineered
PageRank/centrality/clustering features below with learned embeddings.
Not implemented here per scope — see Phase 8 "Future Cash Graph" in spec.
"""
import os
import numpy as np
import pandas as pd
import networkx as nx
import joblib
from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, mean_absolute_error

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(BASE_DIR, "data", "invoices.csv")
ARTIFACT_PATH = os.path.join(BASE_DIR, "models", "artifacts", "graph_risk.joblib")

RELATIONSHIP_TYPES = ["poc", "contract", "recurring"]
TIERS = ["general", "midsize", "large_corp"]
TIER_TRUST = {"large_corp": 95, "midsize": 80, "general": 60}
RECURRING_LAMBDA = {"poc": 0.2, "contract": 1.0, "recurring": 3.0}

FEATURE_COLUMNS = [
    "amount_log", "renewal_rate", "historical_delay_days", "active_recurring_contracts",
    "relationship_type_contract", "relationship_type_recurring",
    "tier_midsize", "tier_large_corp",
    "graph_pagerank", "graph_degree_centrality", "graph_clustering",
]


def _derive_synthetic_context(df: pd.DataFrame, rng: np.random.Generator) -> pd.DataFrame:
    """Adds tier + active_recurring_contracts columns not present in raw invoices.csv,
    consistent with the relationship_type already generated by synth_gen.py."""
    df = df.copy()
    tier_probs = {
        "recurring": [0.15, 0.35, 0.50],
        "contract": [0.35, 0.45, 0.20],
        "poc": [0.60, 0.35, 0.05],
    }
    df["counterparty_tier"] = df["relationship_type"].map(
        lambda rt: rng.choice(TIERS, p=tier_probs[rt])
    )
    df["active_recurring_contracts"] = df["relationship_type"].map(
        lambda rt: rng.poisson(RECURRING_LAMBDA[rt])
    )
    return df


def _build_graph_features(df: pd.DataFrame) -> pd.DataFrame:
    """Builds a bipartite-ish startup<->counterparty graph plus intra-tier
    clustering edges, then computes PageRank/degree-centrality/clustering
    per counterparty node."""
    G = nx.Graph()
    G.add_node("STARTUP")
    for idx, row in df.iterrows():
        node = f"CP_{idx}"
        G.add_node(node)
        weight = float(np.log1p(row["amount"])) * (0.5 + row["network_centrality"])
        G.add_edge("STARTUP", node, weight=weight)

    # counterparties of the same tier/relationship cluster together (peer network effect)
    for tier in df["counterparty_tier"].unique():
        peers = df.index[df["counterparty_tier"] == tier].tolist()
        sample_size = min(len(peers), 6)
        rng = np.random.default_rng(7)
        for idx in peers:
            others = rng.choice(peers, size=min(sample_size, len(peers)), replace=False)
            for other in others:
                if other != idx:
                    G.add_edge(f"CP_{idx}", f"CP_{other}", weight=0.3)

    pagerank = nx.pagerank(G, weight="weight")
    degree_centrality = nx.degree_centrality(G)
    clustering = nx.clustering(G, weight="weight")

    feats = pd.DataFrame(index=df.index)
    feats["graph_pagerank"] = [pagerank[f"CP_{i}"] for i in df.index]
    feats["graph_degree_centrality"] = [degree_centrality[f"CP_{i}"] for i in df.index]
    feats["graph_clustering"] = [clustering[f"CP_{i}"] for i in df.index]
    # normalize pagerank to a comparable 0-1-ish scale
    feats["graph_pagerank"] = feats["graph_pagerank"] / feats["graph_pagerank"].max()
    return feats


def _network_credit_score(row, graph_feats) -> float:
    """Deterministic spec 3-1 formula — used as the training LABEL the
    GBM models learn to reproduce/generalize from raw features."""
    counterparty_trust = TIER_TRUST[row["counterparty_tier"]]
    renewal_rate = row["renewal_rate"]
    payment_reliability = max(0, 100 - row["historical_delay_days"] * 2)
    network_centrality_norm = graph_feats["graph_pagerank"] * 100
    active_recurring = min(100, row["active_recurring_contracts"] * 20)

    score = (
        counterparty_trust * 0.30
        + renewal_rate * 0.25
        + payment_reliability * 0.20
        + network_centrality_norm * 0.15
        + active_recurring * 0.10
    )
    return float(np.clip(score, 0, 100))


def _risk_bucket(score: float) -> str:
    if score >= 70:
        return "low"
    if score >= 40:
        return "medium"
    return "high"


def _build_features(df: pd.DataFrame) -> pd.DataFrame:
    graph_feats = _build_graph_features(df)
    out = pd.DataFrame(index=df.index)
    out["amount_log"] = np.log1p(df["amount"])
    out["renewal_rate"] = df["renewal_rate"]
    out["historical_delay_days"] = df["historical_delay_days"]
    out["active_recurring_contracts"] = df["active_recurring_contracts"]
    out["relationship_type_contract"] = (df["relationship_type"] == "contract").astype(int)
    out["relationship_type_recurring"] = (df["relationship_type"] == "recurring").astype(int)
    out["tier_midsize"] = (df["counterparty_tier"] == "midsize").astype(int)
    out["tier_large_corp"] = (df["counterparty_tier"] == "large_corp").astype(int)
    out[["graph_pagerank", "graph_degree_centrality", "graph_clustering"]] = graph_feats
    return out[FEATURE_COLUMNS], graph_feats


def train(data_path: str = DATA_PATH, artifact_path: str = ARTIFACT_PATH) -> dict:
    rng = np.random.default_rng(11)
    df = pd.read_csv(data_path)
    df = _derive_synthetic_context(df, rng)

    X, graph_feats = _build_features(df)
    scores = df.apply(lambda row: _network_credit_score(row, graph_feats.loc[row.name]), axis=1)
    risk_labels = scores.apply(_risk_bucket)

    X_train, X_test, y_score_train, y_score_test, y_risk_train, y_risk_test = train_test_split(
        X, scores, risk_labels, test_size=0.2, random_state=42, stratify=risk_labels
    )

    clf = GradientBoostingClassifier(random_state=42)
    clf.fit(X_train, y_risk_train)
    risk_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_risk_test, risk_pred)
    f1 = f1_score(y_risk_test, risk_pred, average="macro")

    reg = GradientBoostingRegressor(random_state=42)
    reg.fit(X_train, y_score_train)
    score_pred = reg.predict(X_test)
    mae = mean_absolute_error(y_score_test, score_pred)

    os.makedirs(os.path.dirname(artifact_path), exist_ok=True)
    joblib.dump({"classifier": clf, "regressor": reg}, artifact_path)

    return {
        "model": "graph_risk (networkx features + GradientBoosting)",
        "risk_accuracy": round(float(accuracy), 4),
        "risk_f1_macro": round(float(f1), 4),
        "score_mae": round(float(mae), 3),
        "n_train": len(X_train),
        "n_test": len(X_test),
    }


def load(artifact_path: str = ARTIFACT_PATH) -> dict:
    return joblib.load(artifact_path)


def predict(artifact: dict, features: dict) -> dict:
    """features: renewal_rate, network_centrality, relationship_type,
    historical_delay_days, active_recurring_contracts, counterparty_tier

    A brand-new single counterparty has no position in the training graph,
    so its PageRank/degree/clustering are approximated from the client-supplied
    network_centrality signal (0-1) — a practical proxy in absence of full
    graph context at request time."""
    centrality = features["network_centrality"]
    clustering_prior = {"poc": 0.1, "contract": 0.3, "recurring": 0.5}[features["relationship_type"]]

    row = pd.DataFrame([{
        "amount_log": np.log1p(features.get("amount", 10_000_000)),
        "renewal_rate": features["renewal_rate"],
        "historical_delay_days": features["historical_delay_days"],
        "active_recurring_contracts": features["active_recurring_contracts"],
        "relationship_type_contract": 1 if features["relationship_type"] == "contract" else 0,
        "relationship_type_recurring": 1 if features["relationship_type"] == "recurring" else 0,
        "tier_midsize": 1 if features["counterparty_tier"] == "midsize" else 0,
        "tier_large_corp": 1 if features["counterparty_tier"] == "large_corp" else 0,
        "graph_pagerank": centrality,
        "graph_degree_centrality": centrality,
        "graph_clustering": centrality * clustering_prior,
    }])[FEATURE_COLUMNS]

    clf = artifact["classifier"]
    reg = artifact["regressor"]

    risk = clf.predict(row)[0]
    score = float(np.clip(reg.predict(row)[0], 0, 100))

    return {
        "network_credit_score": round(score, 1),
        "counterparty_risk": risk,
    }


if __name__ == "__main__":
    print(train())
